// <auto-generated />
namespace WebBanGiay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class NormalizeProductData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NormalizeProductData));
        
        string IMigrationMetadata.Id
        {
            get { return "202604170008028_NormalizeProductData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
